DEFINE_ACTION_FUNCTION GET_DLG_WEIGHT
	INT_VAR idx_state = 0
	STR_VAR dlg_file = ~~
	RET weight
BEGIN
	COPY_EXISTING ~%dlg_file%~ ~override~
		READ_LONG 0x08 num_states
		PATCH_IF (idx_state >= num_states) BEGIN
			PATCH_FAIL ~GET_DLG_WEIGHT: In %dlg_file% state %idx_state% is out of bound!~
		END

		READ_LONG 0x0c ofs_states

		READ_LONG (ofs_states + (idx_state * 0x10) + 0xc) weight
	BUT_ONLY
END
