IF
	PickPocketFailed([PC])
	Global("ZorlDopple","GLOBAL",0)
	See(LastTrigger)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@41)
		Wait(2)
		SetGlobal("ZorlDopple","GLOBAL",1)
END

IF
	Global("ZorlDopple","GLOBAL",0)
	!Global("JA#SENDZORL","GLOBAL",2)
	AreaCheck("%SWBaldursGate_MerchantLeague_L2%")
	PartyHasItem("SCRL2P")
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@41)
		Wait(2)
		SetGlobal("ZorlDopple","GLOBAL",1)
END
