///////////////////////////////
// Ender Sai in Baldur's Gate
///////////////////////////////


COPY_EXISTING ~ENDER.CRE~ ~override~
	WRITE_ASCII 0x280 ~ENDER~ #32
BUT_ONLY


COPY_EXISTING ~ENDER.CRE~ ~override/JA#ENSAI.CRE~
	WRITE_BYTE 0x273 4 // Class: Thief
	WRITE_ASCII DIALOG ~JA#ENSAI~ #8


EXTEND_TOP ~%EBaldursGate_Inn_L1_BCS%.BCS~ ~JA#BGT_AdvPack/Ender_Sai/AR7807.BAF~ EVALUATE_BUFFER


COMPILE EVALUATE_BUFFER ~JA#BGT_AdvPack/Ender_Sai/ja#ensai.d~
