///////////////////////////////////
//Backdoor for Waterqueen's House
///////////////////////////////////


COPY_EXISTING ~%BaldursGateDocks%.are~ ~override~
	LPF fj_are_structure
		INT_VAR
		fj_type         = 2    //travel
		fj_box_left     = 605
		fj_box_top      = 2264
		fj_box_right    = 683
		fj_box_bottom   = 2325
		fj_cursor_idx   = 30
		fj_vertex_0     = 605 + (2297 << 16)
		fj_vertex_1     = 634 + (2264 << 16)
		fj_vertex_2     = 683 + (2272 << 16)
		fj_vertex_3     = 649 + (2325 << 16)
		STR_VAR
		fj_structure_type   = region
		fj_name             = ~DOORJA#7609~
		fj_destination_area = EVAL ~%BaldursGateDocks_WaterQueensHouse%~
		fj_destination_name = ~JA#FR8100~
	END
	LPF fj_are_structure
		INT_VAR
		fj_loc_x       = 527
		fj_loc_y       = 2244
		fj_orientation = 6
		STR_VAR
		fj_structure_type = entrance
		fj_name           = ~JA#FR7609~
	END
BUT_ONLY

COPY_EXISTING ~%BaldursGateDocks_WaterQueensHouse%.are~ ~override~
	LPF fj_are_structure
		INT_VAR
		fj_type         = 2    //travel
		fj_box_left     = 298
		fj_box_top      = 559
		fj_box_right    = 342
		fj_box_bottom   = 675
		fj_cursor_idx   = 30
		fj_flags        = (GAME_IS ~bgt~ ? 0 : 0b001000000000) // Cannot be passed by NPC(9)
		fj_vertex_0     = 342 + (624 << 16)
		fj_vertex_1     = 298 + (675 << 16)
		fj_vertex_2     = 298 + (606 << 16)
		fj_vertex_3     = 342 + (559 << 16)
		STR_VAR
		fj_structure_type   = region
		fj_name             = ~DOORJA#81~
		fj_destination_area = EVAL ~%BaldursGateDocks%~
		fj_destination_name = ~JA#FR7609~
	END
	LPF fj_are_structure
		INT_VAR
		fj_loc_x       = 385
		fj_loc_y       = 621
		fj_orientation = 9
		STR_VAR
		fj_structure_type = entrance
		fj_name           = ~JA#FR8100~
	END
BUT_ONLY
