/*
IF
	InMyArea("Abela")
	Exists("Abela")
	OR(2)
		GlobalGT("RamazithMove","GLOBAL",1)
		Global("JA#RamazithDeal","GLOBAL",1)
	Global("JA#MOVE_ABELA","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("JA#MOVE_ABELA","GLOBAL",1)
		ActionOverride("Abela",ForceSpell(Myself,QUICK_TELEPORT))
		// SmallWait(1)
		// ActionOverride("Abela",EscapeAreaDestroy(0))
		ActionOverride("Abela",EscapeAreaDestroy(0))
END
*/
