// Anything to process Aldeth's party


COMPILE EVALUATE_BUFFER ~JA#BGT_AdvPack/Merchants_League/party/JA#CUIRL.BAF~
COMPILE EVALUATE_BUFFER ~JA#BGT_AdvPack/Merchants_League/party/JA#ZORL.BAF~


EXTEND_TOP ~%SWBaldursGate_MerchantLeague_L1_BCS%.BCS~ ~JA#BGT_AdvPack/Merchants_League/party/AR7227.BAF~ EVALUATE_BUFFER
EXTEND_TOP ~%SWBaldursGate_MerchantLeague_L3_BCS%.BCS~ ~JA#BGT_AdvPack/Merchants_League/party/AR7229.BAF~ EVALUATE_BUFFER


COPY_EXISTING ~%SWBaldursGate_MerchantLeague_L2_BCS%.BCS~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		REPLACE_TEXTUALLY ~NumDeadGT("DopZorl",5)~ ~NumDeadGT("DopZorl",9) Dead("Zorl") Dead("Irlentre")~
	END
BUT_ONLY


COMPILE EVALUATE_BUFFER ~JA#BGT_AdvPack/Merchants_League/party/ja#aldeth.d~
COMPILE EVALUATE_BUFFER ~JA#BGT_AdvPack/Merchants_League/party/ja#zorl.d~

// JA#ZORL.BCS is added to ZORL.CRE in ../setup-Merchants_League.tpa

COPY_EXISTING ~%SWBaldursGate_MerchantLeague_L3%.ARE~ ~override~
	LPF DELETE_AREA_ACTOR STR_VAR cre_to_delete = ~DOPPLE~ END
BUT_ONLY
